spring.application.name=return-filing-service
# ==========================
# Database
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/filing_db
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA
# ==========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Flyway
# ==========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration